### ISSUE TITLE
Project Initial Setting

### ISSUE THREAD

**Issue by alpha-kwhn** [GOSOPT-CDS-BAEMIN/iOS#1]
---
name: Baemin Issue Template
about: "배민 이슈 템플릿입니다."
title: "#이슈번호 [Prefix] 이슈 내용"
labels: ''
assignees: ''

---

### 프로젝트 초기 세팅

<br/>

## 📝 To-do

- [x] Custom Issue Template 생성
- [x] Custom PR Template 생성
- [x] Xcode 프로젝트 생성
- [x] Project Foldering
- [x] SwiftLint Setting
- [x] Add Packages
