### ISSUE TITLE
[Add] Image Asset 추가

### ISSUE THREAD

**Issue by alpha-kwhn** [GOSOPT-CDS-BAEMIN/iOS#3]
###  Image Asset 추가하기
<br/>

## 📝 To-do

- [x] Image Asset 이름 설정 
- [x] Image Asset 분류하기
- [x] 프로젝트 Asset에 이미지 추가 (x1, x2, x3)
- [x] 이미지 폴더링
- [x] Extension에서 각각의 이미지 Asset에 대한 상수 선언하기
