### ISSUE TITLE
[Fix] API 수정 

### ISSUE THREAD

**Issue by jeongdung-eo** [GOSOPT-CDS-BAEMIN/iOS#48]
###  탭바 카테고리별 API 내려오는 데이터 수정 

<br/>

## 📝 To-do

- [x] 메인뷰 API 수정 
- [ ] 메뉴디테일뷰 API 수정 
- [x] 리뷰 바텀시트뷰 API 수정
